import { Inter } from 'next/font/google'
import './globals.css'
import Home from './page.js'
import Form from './components/Form'
import 'bootstrap/dist/css/bootstrap.min.css';
import EnhancedTable from './components/EnhancedTable';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        {/* <Form /> */}
        <EnhancedTable />
      </body>
    </html>
  )
}
